apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-mongo-pv
spec:
  storageClassName: authstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db-auth-mongo"
