apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo-pvc
  labels:
    name: orders-mongo-pvc
spec:
  storageClassName: ordersstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
