apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-mongo-pv
spec:
  storageClassName: ordersstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db-orders-mongo"
