apiVersion: v1
kind: PersistentVolume
metadata:
  name: payments-mongo-pv
spec:
  storageClassName: paymentsstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db-payments-mongo"
