apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payments-mongo-pvc
  labels:
    name: payments-mongo-pvc
spec:
  storageClassName: paymentsstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
