apiVersion: v1
kind: PersistentVolume
metadata:
  name: tickets-mongo-pv
spec:
  storageClassName: ticketsstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db-tickets-mongo"
