apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ngtrdai197/microservices_ticketing_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"

    - image: ngtrdai197/microservices_ticketing_tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"

    - image: ngtrdai197/microservices_ticketing_orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"

    - image: ngtrdai197/microservices_ticketing_client_app
      context: client-app
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: .
