apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: ngtrdai197/microservices_ticketing_payments
          env:
            - name: NATS_URL
              value: http://nats-clusterip-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NAST_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGODB_URL
              value: mongodb://payments-mongo-clusterip-srv:27017/mcsv-ticketing-payments
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-clusterip-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
