apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: ngtrdai197/microservices_ticketing_tickets
          env:
            - name: NATS_URL
              value: http://nats-clusterip-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NAST_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGODB_URL
              value: mongodb://tickets-mongo-clusterip-srv:27017/mcsv-ticketing-tickets
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-clusterip-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
